package com.bts.utils;

public enum Type {
	DEVELOPER_REGISTRATION, TESTER_REGISTRATION, DEVELOPER_LIST, TESTER_LIST, PROJECT_LIST, APPROVAL_LIST, TESTER_LOGIN, DEVELOPER_LOGIN,
	WRAPPER_LIST, SAVE_EMPLOYEE_WRAPPER,ADD_PROJECT,UPDATE_PROJECT,GET_PROJ_BY_ID,
	DEVELOPER_HOME, TESTER_HOME, ADMIN_HOME_FETCH_COMPLETED_PROJECTS, ADMIN_HOME_FETCH_LIVE_PROJECTS,
	DEV_HOME_FETCH_DEVELOPER, TEST_HOME_FETCH_TESTER, UPDATE_BUG_LIST, ADD_LINK, FETCH_PROJECT_BY_ID, SET_PROJECT_STATUS_TO_COMPLETE
}
